---
abstract: 'Tapper - Receiver for Tapper test reports'
author:
  - 'AMD OSRC Tapper Team, C<< <tapper at amd64.org> >>'
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Slurp: 0
  Tapper::Test: 3.000002
  Test::More: 0
  Test::Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: freebsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-Reports-Receiver
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  AnyEvent: 0
  Cwd: 0
  DateTime::Format::Mail: 0
  DateTime::Format::Natural: 0
  EV: 0
  File::Basename: 0
  File::MimeInfo::Magic: 0
  File::Spec: 0
  IO::Scalar: 0
  Module::Build: 0
  Moose: 0
  MooseX::Daemonize: 0
  MooseX::Log::Log4perl: 0.42
  Net::Server::PreForkSimple: 0
  TAP::Parser: 0
  Tapper::Config: 3.000002
  Tapper::Schema: 3.000002
  Tapper::TAP::Harness: 3.000002
  perl: 5.010
version: 3.000003
